extends: existence
message: "Feel free to use a contraction instead of '%s':
  https://orbit.kiwi/content/technical-content/language/#use-contractions"
link: https://orbit.kiwi/content/technical-content/language/#use-contractions
level: suggestion
ignorecase: true
scope: raw
tokens:
  - are not
  - cannot
  - could not
  - did not
  - do not
  - does not
  - has not
  - have not
  - is not
  - (?<!(?:where|how|what) )it is
  - should not
  - that is
  - (?<!(?:where|how) )they are
  - was not
  - (?<!(?:where|how) [a-z]* )we are
  - were not
  - what is
  - when is
  - where is
  - will not
  - you are
